### ISSUE TITLE
vaults

### ISSUE THREAD

**Issue by Probe1** [Probe1/vgstation13#4]
a pirate ship

Arcade area with all kinds of fake syndicate stuff
Maybe a Cuban Pete arcade

an island thats just a huge anime shoppe with  counterfeit figurines

Long hallway that's exposed to space and has a door at the end, the door leads to a room that's overpressurised as hell so if you open it without magboots you get shot down the hallway and into space at really high speed
There could be loot and a poster saying MAGBOOTS or something in the room

There's a whole array of advanced clown gear in there, but you have to solve a bunch of riddles and defeat 2 strong clown golems to get access to it.

All with a a tool box in hand as your weapon to show your robustness.

It's full of dogs

**Comment by Probe1** [comment]
spider colony

**Comment by Probe1** [comment]
OOC: Pvak: prison vault
OOC: Pvak: with real police gear

**Comment by Probe1** [comment]
OOC: A bumbling idiot: rename mega mad crab to mr crabs and fill it up with gold bars and coins
OOC: Pvak: also the mega mad crab should be able to shoot fireballs

**Comment by Probe1** [comment]
OOC: HerrytheafroHeadcrab: not enough xenomorph vaults
OOC: A bumbling idiot: eh need more xeno or robot ones

**Comment by Probe1** [comment]
OOC: Spetslana: we need a doomguy vault

**Comment by Probe1** [comment]
OOC: Yelier: It'd be sick as fuck to see a plasmaman station that's perpetually plasmaflooded

**Comment by Probe1** [comment]
OOC: ConSedFu: How about a Virus Vault.

**Comment by 9600bauds** [comment]
![permabotany](https://cloud.githubusercontent.com/assets/6526157/21295657/be45a7c8-c538-11e6-9a01-ff81de6be19b.png)

Observatory

Actually add an observatory to Deff

**Comment by Probe1** [comment]
how did you even find this issue

**Comment by 9600bauds** [comment]
![firefox_2016-12-14_02-43-31](https://cloud.githubusercontent.com/assets/6526157/21295667/ecbf4cd0-c538-11e6-99d3-e7a71ae632fd.png)

**Comment by Probe1** [comment]
will do on the deff observatory

**Comment by Probe1** [comment]
Sober? Acee - Today at 1:54 PM
you could do like a mini resident evil sort of thing. Put a .45 pistol and very limited ammo around. then a bunch of zombies

Sober? Acee - Today at 1:54 PM
and then maybe scatter some tools around for a puzzle or something

**Comment by Probe1** [comment]
3:43 AM - Mr. Pain: Vaults? Havent thought of any yet
3:43 AM - Mr. Pain: I'll get back to you on that
3:43 AM - Mr. Pain: I think there are some clown themed vaults, any mime ones?
3:43 AM - Mr. Pain: Mimes need love too
4:31 AM - Mr. Pain: I've always noticed
4:31 AM - Mr. Pain: You can always "make" clowns with genetics
4:31 AM - Mr. Pain: Give them the clumsy block
4:31 AM - Mr. Pain: But you cant ever give someone a vow of silence
4:31 AM - Mr. Pain: Maybe we can hide a "Shrine of Silence" somewhere
4:32 AM - Mr. Pain: or "Shrine to the Mime Father"
4:32 AM - Probe1: that may be a better course of action
4:32 AM - Mr. Pain: and maybe by the same coin, make a "Shrine of the Honkmother" that gives you clumsy
4:32 AM - Mr. Pain: And both would give you gear and a name change prompt

**Comment by Probe1** [comment]
![ftlgame_2016-12-28_18-34-19](https://cloud.githubusercontent.com/assets/8550416/21533788/56339054-cd2c-11e6-8953-3d1b194a8935.png)
